# Generated by Django 5.2.1 on 2025-06-16 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthStatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'health_statuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NecessaryActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_description', models.CharField(max_length=255)),
                ('urgency', models.IntegerField()),
                ('cause_description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'necessary_actions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trees',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alcaldia', models.CharField(choices=[('alvaro_obregon', 'Alvaro Obregon'), ('azcapotzalco', 'Azcapotzalco'), ('benito_juarez', 'Benito Juarez'), ('coyoacan', 'Coyoacan'), ('cuajimalpa_de_morelos', 'Cuajimalpa de Morelos'), ('cuauhtemoc', 'Cuauhtemoc'), ('gustavo_a_madero', 'Gustavo A. Madero'), ('iztapalapa', 'Iztapalapa'), ('la_magdalena_contreras', 'La Magdalena Contreras'), ('miguel_hidalgo', 'Miguel Hidalgo'), ('milpa_alta', 'Milpa Alta'), ('tlahuac', 'Tlahuac'), ('tlalpan', 'Tlalpan'), ('xochimilco', 'Xochimilco'), ('venustiano_carranza', 'Venustiano Carranza')], max_length=350)),
                ('colonia', models.CharField(max_length=350)),
                ('calle', models.CharField(max_length=500)),
                ('num', models.CharField(max_length=10)),
                ('cp', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('reference', models.CharField(blank=True, max_length=500, null=True)),
                ('height', models.FloatField()),
                ('base_diameter', models.FloatField()),
                ('trunk_diameter', models.FloatField()),
                ('crown_diameter', models.FloatField()),
                ('trunk_inclination', models.FloatField()),
                ('health_status', models.IntegerField()),
                ('last_inspection', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TreeSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tree_species',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrunkStructures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'trunk_structures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tphotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tree_photos/')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='treecontrol1.trees')),
            ],
        ),
    ]
