# Generated by Django 5.2.1 on 2025-06-16 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treecontrol1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tree_photos/')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='treecontrol1.trees')),
            ],
        ),
        migrations.DeleteModel(
            name='tphotos',
        ),
    ]
